Djangolvl5/Djangolvl5/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),
    path('logout/', views.usr_logout, name='logout'),
    path('special/', views.special),
    path('admin/', admin.site.urls),

]

Djangolvl5/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'matcher'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.usr_login, name='usr_login'),
]

Djangolvl5/basic_app/models.py
from django.db import models
from  django.contrib.auth.admin import User

# Create your models here.
class  userprofileinfo(models.Model):
    user =  models.OneToOneField(User,on_delete=models.NullBooleanField)


    profile_link = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profiles',blank=True)

    def __str__(self):
        return self.user.username

Djangolvl5/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import userprofileinfo



class  UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')



class UserprofileForm(forms.ModelForm):
    class Meta():
        model = userprofileinfo
        fields = ('profile_link','profile_pic')

Djangolvl5/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserprofileForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')


@login_required
def usr_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('matcher:index'))

@login_required
def special(request):
    return HttpResponse("You are Logged In")

def register(request):

    registerd = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form =  UserprofileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registerd = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserprofileForm()


    return  render(request,'basic_app/register.html',
            context={'user_form':user_form,'profile_form':profile_form,'registerd':registerd})


def  usr_login(request):
    if request.method == 'POST':
        uid = request.POST.get('inputuid')
        pswd = request.POST.get('inputPassword')
        user = authenticate(username=uid,password=pswd)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('matcher:index'))
            else:
                return HttpResponse("Account  Not Active")

        else:
            print("Someone failed to login \n ")
            print("Username: {} and Password: {}".format(uid,pswd))
            return HttpResponse("Invalid Login Request")
    else:
        return render(request,'basic_app/usr_login.html')

Djangolvl5/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'matcher:index' %}">Brand</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'matcher:register' %}">Register</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'matcher:usr_login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>

</body>
</html>

Djangolvl5/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Django Level 5 Home</h1>
    </div>
{% endblock %}

Djangolvl5/templates/basic_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Djangolvl5/templates/basic_app/register.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}

    <div class="jumbotron">
        {% if registerd %}
            <h1>Thank You for registering</h1>
        {% else %}
            <h1>Register Here</h1>
            <h3>Fill out the form:</h3>
            <form method="post" enctype="multipart/form-data">
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                 {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-sm" value="Submit">
            </form>
    {% endif %}

    </div>

{% endblock %}

Djangolvl5/templates/basic_app/usr_login.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url  'matcher:usr_login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputuid">Username:</label>
                <input type="text" class="form-control" name='inputuid' id="inputuid"  placeholder="Enter Username">
            </div>
            <div class="form-group">
                <label for="inputPassword">Password</label>
                <input type="password" class="form-control" name='inputPassword' id="inputPassword" placeholder="Enter Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}